# Generated by Django 4.2.30 on 2026-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_online_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('rider', 'Rider'), ('driver', 'Driver'), ('admin', 'Admin')], default='rider', max_length=10),
        ),
    ]
