name: Bodaboda CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  ci-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: bodaboda-app
      run: npm install

    - name: Run tests
      working-directory: bodaboda-app
      run: npm test

    - name: Build app
      working-directory: bodaboda-app
      run: npm run build

  docker-build:
    needs: ci-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t bodaboda-app:v1 .

  staging:
    needs: docker-build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Staging
      run: echo "Deploying to STAGING SERVER..."

  production:
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
    - name: Deploy to Production
      run: echo "Deploying to PRODUCTION SERVER..."